[tool.poetry]
name = "scrapp"
version = "0.1.0"
description = ""
authors = ["YG1ee <fanfolderkim@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
requests = "^2.28.1"
beautifulsoup4 = "^4.11.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
